GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Anamara",
    "email": "anamara@email.com"
}

###

GET http://localhost:3000/usuarios/1

###

DELETE http://localhost:3000/usuarios/9

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "Alfonso",
    "email": "alfonso@email.com"
}

//------------------------------------------------------------------------------------------------

GET http://localhost:3000/livros

###

POST http://localhost:3000/livros
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis"
}

###

PUT http://localhost:3000/livros/1
Content-Type: application/json

{
    "titulo": "Dom Casmurro - Atualizado"
}

###

DELETE http://localhost:3000/livros/1